### ISSUE TITLE
Allow customization of ImageView when using Picasso or Glide adapters

### ISSUE THREAD

**Issue by vitorhugods** [ouattararomuald/android-image-slider#44]
Hi man, great work!

Just a quick suggestion for improvement: I had to re-implement the PicassoImageLoader in order to intercept the ImageView and change the `scaleType`.

Maybe make it `open`, so we can get the `imageView` in the `load` method and customize the ImageView.

**Comment by ouattararomuald** [comment]
Hi @vitorhugods thank you :-).
I appreciate your feedback and I'll consider it in the next release.
