### ISSUE TITLE
Request For Turn Off Auto-Cycling

### ISSUE THREAD

**Issue by IrhamMaulani** [ouattararomuald/android-image-slider#51]
Halo, I have read the documentation but there is no function to turn off auto-cycling. Could you add function to turn off auto-cycling? thanks

**Comment by ouattararomuald** [comment]
Hi,
you can turn it off by adding both attributes on your ImageSlider:

```xml
<com.ouattararomuald.slider.ImageSlider
    ...
    app:initWithAutoCycling="false"
    app:autoRecoverAfterTouchEvent="false"
/>
```

You'll have to do it via xml for now. But I'll quickly enable the feature from code. Thanks for you feedback

**Comment by IrhamMaulani** [comment]
oh thank you, this what I need
